words = [
    'electricity', 'donkey', 'hardware', 'xerox', 'transistor', 'computer', 'desktop', 'engineering', 'hangman',
    'circuit', 'imagination', 'robot', 'memory', 'power', 'submarine', 'chess', 'resistance', 'matrix', 'function',
    'laser', 'mechanism', 'bodyguard', 'titanic', 'global', 'ozone', 'bridge', 'technology', 'spider', 'un',
    'pyramid', 'sphere', 'member', 'warning', 'yourself', 'screen', 'language', 'ele', 'system', 'internet',
    'parameter', 'traffic', 'network', 'filter', 'nucleus', 'r', 'automatic', 'microphone', 'cassette', 'operation',
    'country', 'beautiful', 'mis', 'picture', 'teacher', 'superman', 'undertaker', 'alarm', 'process', 'keyboard',
    'electron', 'certificate', 'grandfather', 'landmark', 'relativity', 'eraser', 'a', 'design', 'football', 'human',
    'musician', 'egyptian', 'elephant', 'queen', 'rec', 'message', 'wallpaper', 'nationality', 'answer', 'wrong',
    'statement', 'forest', 'puzzle', 'voltage', 'current', 'mathematics', 'wisdom', 'dream', 'supermarket',
    'database', 'collection', 'barrier', 'project', 'sunlight', 'figure', 'graph', 'battle', 'hundred', 'signal',
    'thousand', 'transformation', 'daughter', 'flower', 'communication', 'microwave', 'electronic', 'peace',
    'wireless', 'delete', 'wind', 'brain', 'control', 'prophet', 'freedom', 'harbour', 'confidence', 'positive',
    'harvest', 'hunger', 'woman', 'children', 'stranger', 'garden', 'pleasure', 'lau', 'between', 'recognition',
    'tomorrow', 'autumn', 'monkey', 'spring', 'winter', 'm', 'classification', 'typewriter', 'success', 'difference',
    'acoustics', 'astronomy', 'agreement', 'sorrow', 'christmas', 'silver', 'birthday', 'championship', 'frien',
    'comfortable', 'diffusion', 'murder', 'policeman', 'science', 'desert', 'basketb', 'blood', 'funeral', 'silence',
    'garment', 'merchant', 'spirit', 'punishment', 's', 'measurement', 'ocean', 'digital', 'illusion', 'tyrant',
    'castle', 'passion', 'p', 'magician', 'remedy', 'knowledge', 'threshold', 'number', 'vision', 'expectation',
    'absence', 'mystery', 'morning', 'device', 'thoughts', 'spirit', 'future', 'impo1', 'mountain', 'treasure',
    'machine', 'whispering', 'eternity', 'reflection', 'occu', 'achievement', 'lightning', 'secret', 'environment',
    'shepherd', 'confusion', 'e', 'grave', 'promise', 'honour', 'reward', 'temple', 'distance', 'eagle', 'saturn',
    'finger', 'belief', 'crystal', 'fashion', 'direction', 'captain', 'moment', 'imp', 'permission', 'logic',
    'analysis', 'password', 'english', 'equalizer', 'simulati', 'emotion', 'battle', 'expression', 'scissors',
    'trousers', 'glasses', 'departmen', 'dictionary', 'chemistry', 'induction', 'detail', 'widow', 'wealth',
    'health', 'disaster', 'volcano', 'poverty', 'limitation', 'perfect', 'intelligence', 'infi', 'failure',
    'ignorance', 'destination', 'source', 'resort', 'satisfaction', 'exam', 'frequency', 'selection', 'substitution',
    'kingdom', 'pattern', 'management', 'e', 'situation', 'multiply', 'treatment', 'dollar', 'intuition', 'chapter',
    'magnet', 'desire', 'command', 'action', 'consciousness', 'enemy', 'security', 'object', 'happen', 'happiness',
    'worry', 'method', 'tolerance', 'error', 'hesitation', 'r', 'record', 'tongue', 'supply', 'vibration', 'stress',
    'despair', 'restaurant', 'm', 'television', 'video', 'audio', 'layer', 'mixture', 'doorbell', 'cousin', 'beard',
    'finance', 'production', 'invisible', 'excitement', 'afternoon', 'office', 'alph', 'illustration', 'valley',
    'apartment', 'necessary', 'shortage', 'almost', 'furni', 'blank']
